import{S as d,i as y}from"./assets/vendor-18365dff.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const h="https://pixabay.com/api/",l={key:"41942411-47547b04f91f4c6a01d45aac7",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:90},g=new d(".gallery a",{overlayOpacity:.8,captionsData:"alt",captionDelay:250}),b=document.querySelector(".gallery-form"),u=document.querySelector(".search-input"),f=document.querySelector(".gallery"),c=document.querySelector(".loader");b.addEventListener("submit",S);function i(o){const r="path/to/your/error.svg";y.show({position:"topRight",iconUrl:r,message:o,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",close:!1,closeOnClick:!0,closeOnEscape:!0})}function S(o){if(o.preventDefault(),!u.value.trim()){i("Please fill in the search field");return}const r=o.currentTarget;L().then(n=>w(n)).catch(n=>i(`Something was wrong ${n}`)).finally(()=>{r.reset(),g.refresh()})}function L(){f.innerHTML="",c.style.display="inline-block",l.q=u.value.trim();const o=new URLSearchParams(l).toString();return fetch(`${h}?${o}`).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).finally(()=>{c.style.display="none"})}function w(o){if(!o.total){i("Sorry, there are no images matching your search query. Please, try again!");return}const r=o.hits.map(({largeImageURL:n,webformatURL:a,tags:e,likes:t,views:s,comments:m,downloads:p})=>`<li class="gallery-item">
          <a href="${n}">
            <img class="api-img" src="${a}" alt="${e}">
            <div class="img-desc">
              <span><b>Likes:</b> <br/>${t}</span>
              <span><b>Views:</b> <br/>${s}</span>
              <span><b>Comments:</b> <br/>${m}</span>
              <span><b>Downloads:</b> <br/>${p}</span>
            </div>
          </a>
        </li>`).join("");f.insertAdjacentHTML("afterbegin",r)}
//# sourceMappingURL=commonHelpers.js.map
